config firewall address
    edit "China"
        set type geography
        set country "CN"
        set color 7
    next
    edit "Singapore"
        set type geography
        set country "SG"
        set color 7
    next
    edit "Russia"
        set type geography
        set country "RU"
        set color 7
    next
    edit "Brazil"
        set type geography
        set country "BR"
        set color 7
    next
    edit "Iran"
        set type geography
        set country "IR"
        set color 7
    next
        edit "Iraq"
        set type geography
        set country "IQ"
        set color 7
    next
        edit "India"
        set type geography
        set country "IN"
        set color 7
    next
    edit "Bangladesh"
        set type geography
        set country "BD"
        set color 7
    next
    edit "Croatia"
        set type geography
        set country "HR"
        set color 7
    next
    edit "Hong Kong"
        set type geography
        set country "HK"
        set color 7
    next
    edit "Pakistan"
        set type geography
        set country "PK"
        set color 7
    next
    edit "USA"
        set type geography
        set country "US"
        set color 15
    next
     edit "Aruba"
        set type geography
        set country "AW"
        set color 7
    next
    edit "Cayman Islands"
        set type geography
        set country "KY"
        set color 7
    next
    edit "Congo"
        set type geography
        set country "CG"
        set color 7
    next
    edit "Kazakhstan"
        set type geography
        set country "KZ"
        set color 7
    next
    edit "Lebanon"
        set type geography
        set country "LB"
        set color 7
    next
    edit "Vietnam"
        set type geography
        set country "VN"
        set color 7
    next
    edit "Ukraine"
        set type geography
        set country "UA"
        set color 7
    next
    edit "North Korea"
        set type geography
        set country "KP"
        set color 7
    next
    edit "Belarus"
        set type geography
        set country "BY"
        set color 7
    next
    edit "Palestinian Territories"
        set type geography
        set country "PS"
        set color 7
    next
end
config firewall addrgrp
    edit "GeoFence"
        set member "Bangladesh" "China" "Croatia" "Hong Kong" "Iran" "Pakistan" "Russia" "Singapore" "Brazil" "Aruba" "Cayman Islands" "Congo" "Kazakhstan" "Lebanon" "Vietnam" "Ukraine" "Belarus" "India" "North Korea" "Pakistan" "Palestinian Territories" "Iraq"
    next
end