config firewall internet-service-group
    edit "Fortinet"
        set direction destination
        set member "Fortinet-DNS" "Fortinet-FTP" "Fortinet-FortiCloud" "Fortinet-FortiClient.EMS" "Fortinet-FortiEDR" "Fortinet-FortiGuard" "Fortinet-FortiGuard.Secure.DNS" "Fortinet-FortiMail.Cloud" "Fortinet-FortiSASE" "Fortinet-FortiVoice.Cloud" "Fortinet-FortiWeb.Cloud" "Fortinet-ICMP" "Fortinet-Inbound_Email" "Fortinet-LDAP" "Fortinet-NTP" "Fortinet-NetBIOS.Name.Service" "Fortinet-NetBIOS.Session.Service" "Fortinet-Other" "Fortinet-Outbound_Email" "Fortinet-RTMP" "Fortinet-SSH" "Fortinet-Web"
    next
    edit "Microsoft"
        set direction destination
        set member "Microsoft-Azure" "Microsoft-Azure.AD" "Microsoft-Azure.Data.Factory" "Microsoft-Azure.Monitor" "Microsoft-Azure.Power.BI" "Microsoft-Azure.SQL" "Microsoft-Azure.Virtual.Desktop" "Microsoft-DNS" "Microsoft-Dynamics" "Microsoft-FTP" "Microsoft-ICMP" "Microsoft-Inbound_Email" "Microsoft-Intune" "Microsoft-LDAP" "Microsoft-Microsoft.Update" "Microsoft-NTP" "Microsoft-NetBIOS.Name.Service" "Microsoft-NetBIOS.Session.Service" "Microsoft-Office365" "Microsoft-Office365.Published" "Microsoft-Office365.Published.Allow" "Microsoft-Office365.Published.Optimize" "Microsoft-Office365.Published.USGOV" "Microsoft-Other" "Microsoft-Outbound_Email" "Microsoft-Outlook" "Microsoft-RTMP" "Microsoft-SSH" "Microsoft-Skype_Teams" "Microsoft-Teams.Published.Worldwide.Allow" "Microsoft-Teams.Published.Worldwide.Optimize" "Microsoft-WNS" "Microsoft-Web"
    next
    edit "TrendMicro"
        set direction destination
        set member "TrendMicro-DNS" "TrendMicro-FTP" "TrendMicro-ICMP" "TrendMicro-Inbound_Email" "TrendMicro-LDAP" "TrendMicro-NTP" "TrendMicro-NetBIOS.Name.Service" "TrendMicro-NetBIOS.Session.Service" "TrendMicro-Other" "TrendMicro-Outbound_Email" "TrendMicro-RTMP" "TrendMicro-SSH" "TrendMicro-Web"
    next
    edit "Cisco"
        set direction destination
        set member "Cisco-DNS" "Cisco-Duo.Security"
    next
    edit "Okta"
        set direction destination
        set member "Okta-DNS" "Okta-FTP" "Okta-ICMP" "Okta-Inbound_Email" "Okta-LDAP" "Okta-NTP" "Okta-NetBIOS.Name.Service" "Okta-NetBIOS.Session.Service" "Okta-Okta" "Okta-Other" "Okta-Outbound_Email" "Okta-RTMP" "Okta-SSH" "Okta-Web"
    next
    edit "vmware"
        set direction destination
        set member "VMware-DNS" "VMware-FTP" "VMware-ICMP" "VMware-Inbound_Email" "VMware-LDAP" "VMware-NTP" "VMware-NetBIOS.Name.Service" "VMware-NetBIOS.Session.Service" "VMware-Other" "VMware-Outbound_Email" "VMware-RTMP" "VMware-SSH" "VMware-Web" "VMware-Workspace.ONE"
    next
end


