config firewall address
    edit "IC360-BHM-UNITI"
        set subnet 216.170.86.64 255.255.255.224
    next
    edit "IC360-BHM-SPECTRUM"
        set subnet 71.45.231.185 255.255.255.248
    next
    edit "IC360-MGM-ATT"
        set subnet 209.214.108.121 255.255.255.248
    next
    edit "IC360-MGM-SPECTRUM"
        set subnet 71.8.34.21 255.255.255.252
    next
    edit "IC360-JAX-UNITI"
        set subnet 142.190.0.241 255.255.255.240
    next
    edit "IC360-JAX-COMCAST"
        set subnet 75.147.174.254 255.255.255.248
    next
    edit "IC360-MEM-AIRESPRING"
        set subnet 12.169.246.201 255.255.255.248
    next
    edit "IC360-MEM-COMCAST"
        set subnet 96.94.195.62 255.255.255.248
    next
    edit "thrive-198.168.31.0/26"
        set comment "thrive East2"
        set subnet 198.168.31.0 255.255.255.192
    next
    edit "thrive-74.220.86.0/26"
        set comment "thrive South1"
        set subnet 74.220.86.0 255.255.255.192
    next
    edit "thrive-Bastion"
        set comment "thrive Azure"
        set subnet 23.100.84.206 255.255.255.255
    next
    edit "10.0.0.0/8"
        set comment "RFC1918 10 net"
        set subnet 10.0.0.0 255.0.0.0
    next
    edit "172.16.0.0/12"
        set comment "RFC1918 172 net"
        set subnet 172.16.0.0 255.240.0.0
    next
    edit "192.168.0.0/16"
        set comment "RFC1918 192 net"
        set subnet 192.168.0.0 255.255.0.0
    next
end
config firewall addrgrp
    edit "thrive-admin-access"
        set member "thrive-74.220.86.0/26" "thrive-198.168.31.0/26" "thrive-Bastion" "IC360-BHM-UNITI" "IC360-BHM-SPECTRUM" "IC360-MGM-ATT" "IC360-MGM-SPECTRUM" "IC360-JAX-UNITI" "IC360-JAX-COMCAST" "IC360-MEM-AIRESPRING" "IC360-MEM-COMCAST" "10.0.0.0/8" "172.16.0.0/12" "192.168.0.0/16"
    next
end
config firewall service custom
    edit "admin-tcp11443"
        set comment "web admin access port"
        set tcp-portrange 11443
    next
    edit "admin-tcp5001"
        set comment "web admin access port"
        set tcp-portrange 5001
    next
    edit "Thrive-FMG541"
        set tcp-portrange 541
    next
    edit "admin-tcp22"
        set comment "ssh port"
        set tcp-portrange 22
    next
    edit "admin-ping"
        set protocol ICMP
        unset icmptype
    next
    edit "admin_snmp"
        set tcp-portrange 161-162
        set udp-portrange 161-162
    next
end
config firewall service group
    edit "system-admin"
        set member "admin-tcp5001" "admin_snmp" "admin-ping" "Thrive-FMG541" "admin-tcp22" "admin-tcp11443" "HTTP" "HTTPS"
    next
end
config firewall local-in-policy
    edit 1
        set intf "any"
        set srcaddr "thrive-admin-access"
        set dstaddr "all"
        set action accept
        set service "system-admin"
        set schedule "always"
    next
    edit 2
        set intf "any"
        set srcaddr "all"
        set dstaddr "all"
        set service "system-admin"
        set schedule "always"
    next
end